//
//  MTLExpressionGoldens.swift
//  MTL
//
//  Created by Rene Hexel on 5/10/2026.
//  Copyright (c) 2026 Rene Hexel. All rights reserved.
//

/// The printed trees of the expressions of ``MTLExpressionCorpus``, recorded from the parser
/// before the expression grammar moved to the AQL package.
///
/// Entries are keyed by expression source. They are part of the specification of the
/// expression grammar and must not change when the parser is restructured.
enum MTLExpressionGoldens {

    /// The printed tree for each expression of ``MTLExpressionCorpus/valid``.
    static let trees: [String: String] = [
    "42": "lit(int(42))",
    "0": "lit(int(0))",
    "-7": "lit(int(-7))",
    "3.14": "lit(real(3.14))",
    "-0.5": "lit(real(-0.5))",
    "\'text\'": "lit(string(\"text\"))",
    "\'\'": "lit(string(\"\"))",
    "\'it\'\'s\'": "lit(string(\"it\'s\"))",
    "\'tab\\there\\nnewline \\\\ \\\' A\'": "lit(string(\"tab\\there\\nnewline \\\\ \' A\"))",
    "true": "lit(bool(true))",
    "false": "lit(bool(false))",
    "null": "lit(null)",
    "x": "var(x)",
    "self": "var(self)",
    "stateIdx": "var(stateIdx)",
    "arr.arrangementName": "nav(var(arr), arrangementName, nullSafe: true)",
    "sm.initialState.onEntry.statements": "nav(nav(nav(var(sm), initialState, nullSafe: true), onEntry, nullSafe: true), statements, nullSafe: true)",
    "tr.sourceState.stateName": "nav(nav(var(tr), sourceState, nullSafe: true), stateName, nullSafe: true)",
    "x.size": "nav(var(x), size, nullSafe: true)",
    "(a).b": "nav(var(a), b, nullSafe: true)",
    "x.oclAsType(Foo).bar.baz": "nav(nav(call(var(x), oclAsType, arrow: false, args: [var(Foo)]), bar, nullSafe: true), baz, nullSafe: true)",
    "x.select": "nav(var(x), select, nullSafe: true)",
    "x.if": "nav(var(x), if, nullSafe: true)",
    "getVersion()": "invoke(-, getVersion, args: [])",
    "add(10, 20)": "invoke(-, add, args: [lit(int(10)), lit(int(20))])",
    "fullName(\'John\', \'Doe\')": "invoke(-, fullName, args: [lit(string(\"John\")), lit(string(\"Doe\"))])",
    "greet(name)": "invoke(-, greet, args: [var(name)])",
    "s.toUpperCase()": "invoke(var(s), toUpperCase, args: [])",
    "a.b(c, d.e)": "invoke(var(a), b, args: [var(c), nav(var(d), e, nullSafe: true)])",
    "min(1, 2)": "invoke(-, min, args: [lit(int(1)), lit(int(2))])",
    "abs(x)": "invoke(-, abs, args: [var(x)])",
    "toString(1)": "invoke(-, toString, args: [lit(int(1))])",
    "Sequence{\'a\', \'b\'}.item()": "invoke(literalCollection(Sequence, [lit(string(\"a\")), lit(string(\"b\"))]), item, args: [])",
    "x.oclIsUndefined()": "call(var(x), oclIsUndefined, arrow: false, args: [])",
    "oclIsUndefined()": "call(var(self), oclIsUndefined, arrow: false, args: [])",
    "f(g(h(1)))": "invoke(-, f, args: [invoke(-, g, args: [invoke(-, h, args: [lit(int(1))])])])",
    "self.describe(n)": "invoke(var(self), describe, args: [var(n)])",
    "items->select(x | x > 1)": "collection(select, var(items), iterator: x, body: binary(>, var(x), lit(int(1))))",
    "items->select(x : Integer | x > 1)->size()": "collection(size, collection(select, var(items), iterator: x, body: binary(>, var(x), lit(int(1)))), iterator: -, body: -)",
    "Sequence{1, 2}->exists(x | x = 2)": "collection(exists, literalCollection(Sequence, [lit(int(1)), lit(int(2))]), iterator: x, body: binary(=, var(x), lit(int(2))))",
    "Sequence{3, 1, 2}->first()": "collection(first, literalCollection(Sequence, [lit(int(3)), lit(int(1)), lit(int(2))]), iterator: -, body: -)",
    "Sequence{3, 1, 2}->last": "collection(last, literalCollection(Sequence, [lit(int(3)), lit(int(1)), lit(int(2))]), iterator: -, body: -)",
    "Sequence{\'a\', \'bb\'}->select(size() > 1)->size()": "collection(size, collection(select, literalCollection(Sequence, [lit(string(\"a\")), lit(string(\"bb\"))]), iterator: self, body: binary(>, invoke(var(self), size, args: []), lit(int(1)))), iterator: -, body: -)",
    "xs->select(oclIsKindOf(EClass))": "collection(select, var(xs), iterator: self, body: call(var(self), oclIsKindOf, arrow: false, args: [var(EClass)]))",
    "xs->reject(x | x.isEmpty())": "collection(reject, var(xs), iterator: x, body: invoke(var(x), isEmpty, args: []))",
    "xs->collect(x | x.name)": "collection(collect, var(xs), iterator: x, body: nav(var(x), name, nullSafe: true))",
    "xs->collect(name)": "collection(collect, var(xs), iterator: self, body: var(name))",
    "xs->any(x | x = 1)": "collection(any, var(xs), iterator: x, body: binary(=, var(x), lit(int(1))))",
    "xs->forAll(x | x > 0)": "collection(forAll, var(xs), iterator: x, body: binary(>, var(x), lit(int(0))))",
    "xs->forAll(y : Integer | y > 0)": "collection(forAll, var(xs), iterator: y, body: binary(>, var(y), lit(int(0))))",
    "xs->exists(size() > 0)": "collection(exists, var(xs), iterator: self, body: binary(>, invoke(var(self), size, args: []), lit(int(0))))",
    "xs->isEmpty()": "collection(isEmpty, var(xs), iterator: -, body: -)",
    "xs->notEmpty()": "collection(notEmpty, var(xs), iterator: -, body: -)",
    "xs->size": "collection(size, var(xs), iterator: -, body: -)",
    "xs->indexOf(y)": "collection(indexOf, var(xs), iterator: -, body: var(y))",
    "sm.states->indexOf(tr.sourceState) - 1 + 2": "binary(+, binary(-, collection(indexOf, nav(var(sm), states, nullSafe: true), iterator: -, body: nav(var(tr), sourceState, nullSafe: true)), lit(int(1))), lit(int(2)))",
    "arr.stateMachine->size() - 1": "binary(-, collection(size, nav(var(arr), stateMachine, nullSafe: true), iterator: -, body: -), lit(int(1)))",
    "xs->sortedBy(x | x.name)": "call(var(xs), sortedBy, arrow: true, args: [lambda(x, nav(var(x), name, nullSafe: true))])",
    "xs->sortedBy(name)": "call(var(xs), sortedBy, arrow: true, args: [lambda(self, var(name))])",
    "xs->closure(x | x.children)": "call(var(xs), closure, arrow: true, args: [lambda(x, nav(var(x), children, nullSafe: true))])",
    "xs->one(x | x = 1)": "call(var(xs), one, arrow: true, args: [lambda(x, binary(=, var(x), lit(int(1))))])",
    "xs->isUnique(name)": "call(var(xs), isUnique, arrow: true, args: [lambda(self, var(name))])",
    "xs->including(1)": "call(var(xs), including, arrow: true, args: [lit(int(1))])",
    "xs->union(ys)->asSet()": "call(call(var(xs), union, arrow: true, args: [var(ys)]), asSet, arrow: true, args: [])",
    "xs->count(1)": "call(var(xs), count, arrow: true, args: [lit(int(1))])",
    "xs->at(1)": "call(var(xs), at, arrow: true, args: [lit(int(1))])",
    "xs->sum()": "call(var(xs), sum, arrow: true, args: [])",
    "xs->select(a | a.b->exists(c | c = a))": "collection(select, var(xs), iterator: a, body: collection(exists, nav(var(a), b, nullSafe: true), iterator: c, body: binary(=, var(c), var(a))))",
    "xs->select(size() > ys->size())": "collection(select, var(xs), iterator: self, body: binary(>, invoke(var(self), size, args: []), collection(size, var(ys), iterator: -, body: -)))",
    "xs->filter(Foo)": "call(var(xs), filter, arrow: true, args: [var(Foo)])",
    "xs->select(x | true)->collect(y | y.n)->asSequence()": "call(collection(collect, collection(select, var(xs), iterator: x, body: lit(bool(true))), iterator: y, body: nav(var(y), n, nullSafe: true)), asSequence, arrow: true, args: [])",
    "f(x | x + 1)": "invoke(-, f, args: [lambda(x, binary(+, var(x), lit(int(1))))])",
    "f(x : Integer | x + 1, 2)": "invoke(-, f, args: [lambda(x, binary(+, var(x), lit(int(1)))), lit(int(2))])",
    "xs.apply(a | a.b)": "invoke(var(xs), apply, args: [lambda(a, nav(var(a), b, nullSafe: true))])",
    "let r = 7 mod 3 in r + 1": "let([r=binary(mod, lit(int(7)), lit(int(3)))], binary(+, var(r), lit(int(1))))",
    "let x = 1, y = 2 in x + y": "let([x=lit(int(1)), y=lit(int(2))], binary(+, var(x), var(y)))",
    "let n : Integer = 1 in n": "let([n=lit(int(1))], var(n))",
    "let s : Sequence(String) = Sequence{} in s": "let([s=literalCollection(Sequence, [])], var(s))",
    "let x = 1 in let y = x in y": "let([x=lit(int(1))], let([y=var(x)], var(y)))",
    "if n > 1 then \'many\' else \'one\' endif": "if(binary(>, var(n), lit(int(1))), lit(string(\"many\")), lit(string(\"one\")))",
    "if (1 > 2) then \'a\' else if (2 > 1) then \'b\' else \'c\' endif endif": "if(binary(>, lit(int(1)), lit(int(2))), lit(string(\"a\")), if(binary(>, lit(int(2)), lit(int(1))), lit(string(\"b\")), lit(string(\"c\"))))",
    "\'<\' + if true then \'x\' else \'y\' endif + \'>\'": "binary(+, binary(+, lit(string(\"<\")), if(lit(bool(true)), lit(string(\"x\")), lit(string(\"y\")))), lit(string(\">\")))",
    "if a and b then 1 else 2 endif": "if(binary(and, var(a), var(b)), lit(int(1)), lit(int(2)))",
    "if x.oclIsUndefined() then 0 else x.size endif": "if(call(var(x), oclIsUndefined, arrow: false, args: []), lit(int(0)), nav(var(x), size, nullSafe: true))",
    "1 + 2 + 3": "binary(+, binary(+, lit(int(1)), lit(int(2))), lit(int(3)))",
    "10 - 4": "binary(-, lit(int(10)), lit(int(4)))",
    "5 + 3": "binary(+, lit(int(5)), lit(int(3)))",
    "6 * 7": "binary(*, lit(int(6)), lit(int(7)))",
    "10 / 4": "binary(/, lit(int(10)), lit(int(4)))",
    "7 mod 3": "binary(mod, lit(int(7)), lit(int(3)))",
    "7 div 3": "binary(div, lit(int(7)), lit(int(3)))",
    "1 + 2 * 3": "binary(+, lit(int(1)), binary(*, lit(int(2)), lit(int(3))))",
    "(1 + 2) * 3": "binary(*, binary(+, lit(int(1)), lit(int(2))), lit(int(3)))",
    "1 - 2 - 3": "binary(-, binary(-, lit(int(1)), lit(int(2))), lit(int(3)))",
    "8 / 4 / 2": "binary(/, binary(/, lit(int(8)), lit(int(4))), lit(int(2)))",
    "2 * 3 / 4 mod 5": "binary(mod, binary(/, binary(*, lit(int(2)), lit(int(3))), lit(int(4))), lit(int(5)))",
    "200 + (stateIdx * 100)": "binary(+, lit(int(200)), binary(*, var(stateIdx), lit(int(100))))",
    "baseLocationId + sm.states->indexOf(tr.targetState) - 1 + 2": "binary(+, binary(-, binary(+, var(baseLocationId), collection(indexOf, nav(var(sm), states, nullSafe: true), iterator: -, body: nav(var(tr), targetState, nullSafe: true))), lit(int(1))), lit(int(2)))",
    "\'Hello\' + \' \' + \'World\'": "binary(+, binary(+, lit(string(\"Hello\")), lit(string(\" \"))), lit(string(\"World\")))",
    "firstName + \' \' + lastName": "binary(+, binary(+, var(firstName), lit(string(\" \"))), var(lastName))",
    "a = b": "binary(=, var(a), var(b))",
    "a <> b": "binary(<>, var(a), var(b))",
    "a < b": "binary(<, var(a), var(b))",
    "a > b": "binary(>, var(a), var(b))",
    "a <= b": "binary(<=, var(a), var(b))",
    "a >= b": "binary(>=, var(a), var(b))",
    "a = b = c": "binary(=, binary(=, var(a), var(b)), var(c))",
    "1 + 2 = 3": "binary(=, binary(+, lit(int(1)), lit(int(2))), lit(int(3)))",
    "a < b + 1": "binary(<, var(a), binary(+, var(b), lit(int(1))))",
    "a and b": "binary(and, var(a), var(b))",
    "a or b": "binary(or, var(a), var(b))",
    "a xor b": "binary(xor, var(a), var(b))",
    "a implies b": "binary(implies, var(a), var(b))",
    "a and b or c": "binary(or, binary(and, var(a), var(b)), var(c))",
    "a or b and c": "binary(or, var(a), binary(and, var(b), var(c)))",
    "a or b xor c": "binary(xor, binary(or, var(a), var(b)), var(c))",
    "a and b and c": "binary(and, binary(and, var(a), var(b)), var(c))",
    "a implies b implies c": "binary(implies, var(a), binary(implies, var(b), var(c)))",
    "a or b implies c and d": "binary(implies, binary(or, var(a), var(b)), binary(and, var(c), var(d)))",
    "a = 1 and b = 2 or c = 3": "binary(or, binary(and, binary(=, var(a), lit(int(1))), binary(=, var(b), lit(int(2)))), binary(=, var(c), lit(int(3))))",
    "(a or b) and c": "binary(and, binary(or, var(a), var(b)), var(c))",
    "a - -1": "binary(-, var(a), lit(int(-1)))",
    "a-1": "binary(-, var(a), lit(int(1)))",
    "a -1": "binary(-, var(a), lit(int(1)))",
    "x.y-1": "binary(-, nav(var(x), y, nullSafe: true), lit(int(1)))",
    "f()-1": "binary(-, invoke(-, f, args: []), lit(int(1)))",
    "1-1": "binary(-, lit(int(1)), lit(int(1)))",
    "a*-1": "binary(*, var(a), lit(int(-1)))",
    "a.size() / 2": "binary(/, invoke(var(a), size, args: []), lit(int(2)))",
    "not a": "unary(not, var(a))",
    "not not a": "unary(not, unary(not, var(a)))",
    "-a": "unary(-, var(a))",
    "- -a": "unary(-, unary(-, var(a)))",
    "-(1 + 2)": "unary(-, binary(+, lit(int(1)), lit(int(2))))",
    "not a and b": "binary(and, unary(not, var(a)), var(b))",
    "-a * b": "binary(*, unary(-, var(a)), var(b))",
    "not x.isEmpty()": "unary(not, invoke(var(x), isEmpty, args: []))",
    "-x.size": "unary(-, nav(var(x), size, nullSafe: true))",
    "- 1": "unary(-, lit(int(1)))",
    "not (a or b)": "unary(not, binary(or, var(a), var(b)))",
    "Sequence{}": "literalCollection(Sequence, [])",
    "Sequence{1, 2, 3}": "literalCollection(Sequence, [lit(int(1)), lit(int(2)), lit(int(3))])",
    "OrderedSet{1, 2}": "literalCollection(OrderedSet, [lit(int(1)), lit(int(2))])",
    "Set{\'a\'}": "literalCollection(Set, [lit(string(\"a\"))])",
    "Bag{\'a\', \'a\'}": "literalCollection(Bag, [lit(string(\"a\")), lit(string(\"a\"))])",
    "Collection{1}": "literalCollection(Sequence, [lit(int(1))])",
    "Sequence{1 + 1, f(x), Sequence{2}}": "literalCollection(Sequence, [binary(+, lit(int(1)), lit(int(1))), invoke(-, f, args: [var(x)]), literalCollection(Sequence, [lit(int(2))])])",
    "Sequence{\'a\', \'b\', \'c\'}->size()": "collection(size, literalCollection(Sequence, [lit(string(\"a\")), lit(string(\"b\")), lit(string(\"c\"))]), iterator: -, body: -)",
    "Sequence{1, 2}.item()": "invoke(literalCollection(Sequence, [lit(int(1)), lit(int(2))]), item, args: [])",
    "ecore::EClass": "type(ecore, EClass)",
    "pkg::Enum::literal": "enum(pkg, Enum, literal)",
    "a::b::Enum::literal": "enum(a::b, Enum, literal)",
    "x.oclIsKindOf(ecore::EClass)": "call(var(x), oclIsKindOf, arrow: false, args: [type(ecore, EClass)])",
    "e.oclIsKindOf(AndExpression)": "call(var(e), oclIsKindOf, arrow: false, args: [var(AndExpression)])",
    "e.oclIsTypeOf(a::b::C)": "call(var(e), oclIsTypeOf, arrow: false, args: [type(a::b, C)])",
    "e.oclAsType(p::q::r::T).name": "nav(call(var(e), oclAsType, arrow: false, args: [type(p::q::r, T)]), name, nullSafe: true)",
    "oclIsKindOf(ecore::EClass)": "call(var(self), oclIsKindOf, arrow: false, args: [type(ecore, EClass)])",
    "xs->select(oclIsKindOf(a::B::C))": "collection(select, var(xs), iterator: self, body: call(var(self), oclIsKindOf, arrow: false, args: [type(a::B, C)]))",
    "xs->filter(pkg::Type)": "call(var(xs), filter, arrow: true, args: [type(pkg, Type)])",
    "x = pkg::Enum::literal": "binary(=, var(x), enum(pkg, Enum, literal))",
    "x = ecore::EClass": "binary(=, var(x), type(ecore, EClass))",
    "e.oclIsKindOf(T)": "call(var(e), oclIsKindOf, arrow: false, args: [var(T)])",
    "e.oclIsTypeOf(T)": "call(var(e), oclIsTypeOf, arrow: false, args: [var(T)])",
    "e.oclAsType(T)": "call(var(e), oclAsType, arrow: false, args: [var(T)])",
    "oclAsType(T)": "call(var(self), oclAsType, arrow: false, args: [var(T)])",
    "e.oclAsType(IntegerConstant).anIntegerValue": "nav(call(var(e), oclAsType, arrow: false, args: [var(IntegerConstant)]), anIntegerValue, nullSafe: true)",
    "tr.booleanExpression.oclAsType(NotExpression).theExpression.oclAsType(EqualExpression).leftExpression.oclAsType(IntegerConstant).anIntegerValue": "nav(call(nav(call(nav(call(nav(var(tr), booleanExpression, nullSafe: true), oclAsType, arrow: false, args: [var(NotExpression)]), theExpression, nullSafe: true), oclAsType, arrow: false, args: [var(EqualExpression)]), leftExpression, nullSafe: true), oclAsType, arrow: false, args: [var(IntegerConstant)]), anIntegerValue, nullSafe: true)",
    "(x)": "var(x)",
    "((x))": "var(x)",
    "(a + b).size": "nav(binary(+, var(a), var(b)), size, nullSafe: true)",
    "(xs->select(x | x > 1))->size()": "collection(size, collection(select, var(xs), iterator: x, body: binary(>, var(x), lit(int(1)))), iterator: -, body: -)",
    "xs->select(x | x > 1 and x < 5)->collect(x | x * 2)->first()": "collection(first, collection(collect, collection(select, var(xs), iterator: x, body: binary(and, binary(>, var(x), lit(int(1))), binary(<, var(x), lit(int(5))))), iterator: x, body: binary(*, var(x), lit(int(2)))), iterator: -, body: -)",
    "if xs->isEmpty() then \'none\' else xs->first().name endif": "if(collection(isEmpty, var(xs), iterator: -, body: -), lit(string(\"none\")), nav(collection(first, var(xs), iterator: -, body: -), name, nullSafe: true))",
    "let n = xs->size() in if n > 1 then n - 1 else 0 endif": "let([n=collection(size, var(xs), iterator: -, body: -)], if(binary(>, var(n), lit(int(1))), binary(-, var(n), lit(int(1))), lit(int(0))))",
    "not xs->exists(x | x.oclIsKindOf(Foo) and x.name = \'a\')": "unary(not, collection(exists, var(xs), iterator: x, body: binary(and, call(var(x), oclIsKindOf, arrow: false, args: [var(Foo)]), binary(=, nav(var(x), name, nullSafe: true), lit(string(\"a\"))))))",
    "a.b(c)->select(d | d.e(f))->size() + g(h)": "binary(+, collection(size, collection(select, invoke(var(a), b, args: [var(c)]), iterator: d, body: invoke(var(d), e, args: [var(f)])), iterator: -, body: -), invoke(-, g, args: [var(h)]))",
    "Sequence{a, b}->collect(x | x.name + \'!\')": "collection(collect, literalCollection(Sequence, [var(a), var(b)]), iterator: x, body: binary(+, nav(var(x), name, nullSafe: true), lit(string(\"!\"))))",
    "self.name + \'.\' + self.kind.toString()": "binary(+, binary(+, nav(var(self), name, nullSafe: true), lit(string(\".\"))), invoke(nav(var(self), kind, nullSafe: true), toString, args: []))",
    "xs->collect(x | x->select(y | y > x))": "collection(collect, var(xs), iterator: x, body: collection(select, var(x), iterator: y, body: binary(>, var(y), var(x))))",
    "xs->select(x | ys->exists(y | y = x))->size() > 0": "binary(>, collection(size, collection(select, var(xs), iterator: x, body: collection(exists, var(ys), iterator: y, body: binary(=, var(y), var(x)))), iterator: -, body: -), lit(int(0)))",
    ]
}
