//
//  MTLExpressionCorpus.swift
//  MTL
//
//  Created by Rene Hexel on 5/10/2026.
//  Copyright (c) 2026 Rene Hexel. All rights reserved.
//

/// The expressions whose parsed trees are recorded in ``MTLExpressionGoldens``.
///
/// The expressions come from the example templates, the conformance templates, the syntax
/// reference, and the expression syntax tests. Each is a complete expression as written inside
/// `[` ... `/]`.
enum MTLExpressionCorpus {

    /// Expressions that must parse, by category.
    static let valid: [(category: String, source: String)] = [
        // Literals
        ("literal", "42"),
        ("literal", "0"),
        ("literal", "-7"),
        ("literal", "3.14"),
        ("literal", "-0.5"),
        ("literal", "'text'"),
        ("literal", "''"),
        ("literal", "'it''s'"),
        ("literal", #"'tab\there\nnewline \\ \' A'"#),
        ("literal", "true"),
        ("literal", "false"),
        ("literal", "null"),

        // Names and navigation
        ("name", "x"),
        ("name", "self"),
        ("name", "stateIdx"),
        ("navigation", "arr.arrangementName"),
        ("navigation", "sm.initialState.onEntry.statements"),
        ("navigation", "tr.sourceState.stateName"),
        ("navigation", "x.size"),
        ("navigation", "(a).b"),
        ("navigation", "x.oclAsType(Foo).bar.baz"),
        ("navigation", "x.select"),
        ("navigation", "x.if"),

        // Calls
        ("call", "getVersion()"),
        ("call", "add(10, 20)"),
        ("call", "fullName('John', 'Doe')"),
        ("call", "greet(name)"),
        ("call", "s.toUpperCase()"),
        ("call", "a.b(c, d.e)"),
        ("call", "min(1, 2)"),
        ("call", "abs(x)"),
        ("call", "toString(1)"),
        ("call", "Sequence{'a', 'b'}.item()"),
        ("call", "x.oclIsUndefined()"),
        ("call", "oclIsUndefined()"),
        ("call", "f(g(h(1)))"),
        ("call", "self.describe(n)"),

        // Arrow calls and collection operations
        ("arrow", "items->select(x | x > 1)"),
        ("arrow", "items->select(x : Integer | x > 1)->size()"),
        ("arrow", "Sequence{1, 2}->exists(x | x = 2)"),
        ("arrow", "Sequence{3, 1, 2}->first()"),
        ("arrow", "Sequence{3, 1, 2}->last"),
        ("arrow", "Sequence{'a', 'bb'}->select(size() > 1)->size()"),
        ("arrow", "xs->select(oclIsKindOf(EClass))"),
        ("arrow", "xs->reject(x | x.isEmpty())"),
        ("arrow", "xs->collect(x | x.name)"),
        ("arrow", "xs->collect(name)"),
        ("arrow", "xs->any(x | x = 1)"),
        ("arrow", "xs->forAll(x | x > 0)"),
        ("arrow", "xs->forAll(y : Integer | y > 0)"),
        ("arrow", "xs->exists(size() > 0)"),
        ("arrow", "xs->isEmpty()"),
        ("arrow", "xs->notEmpty()"),
        ("arrow", "xs->size"),
        ("arrow", "xs->indexOf(y)"),
        ("arrow", "sm.states->indexOf(tr.sourceState) - 1 + 2"),
        ("arrow", "arr.stateMachine->size() - 1"),
        ("arrow", "xs->sortedBy(x | x.name)"),
        ("arrow", "xs->sortedBy(name)"),
        ("arrow", "xs->closure(x | x.children)"),
        ("arrow", "xs->one(x | x = 1)"),
        ("arrow", "xs->isUnique(name)"),
        ("arrow", "xs->including(1)"),
        ("arrow", "xs->union(ys)->asSet()"),
        ("arrow", "xs->count(1)"),
        ("arrow", "xs->at(1)"),
        ("arrow", "xs->sum()"),
        ("arrow", "xs->select(a | a.b->exists(c | c = a))"),
        ("arrow", "xs->select(size() > ys->size())"),
        ("arrow", "xs->filter(Foo)"),
        ("arrow", "xs->select(x | true)->collect(y | y.n)->asSequence()"),

        // Lambdas as call arguments
        ("lambda", "f(x | x + 1)"),
        ("lambda", "f(x : Integer | x + 1, 2)"),
        ("lambda", "xs.apply(a | a.b)"),

        // Let and conditional
        ("let", "let r = 7 mod 3 in r + 1"),
        ("let", "let x = 1, y = 2 in x + y"),
        ("let", "let n : Integer = 1 in n"),
        ("let", "let s : Sequence(String) = Sequence{} in s"),
        ("let", "let x = 1 in let y = x in y"),
        ("conditional", "if n > 1 then 'many' else 'one' endif"),
        ("conditional", "if (1 > 2) then 'a' else if (2 > 1) then 'b' else 'c' endif endif"),
        ("conditional", "'<' + if true then 'x' else 'y' endif + '>'"),
        ("conditional", "if a and b then 1 else 2 endif"),
        ("conditional", "if x.oclIsUndefined() then 0 else x.size endif"),

        // Operators and precedence
        ("binary", "1 + 2 + 3"),
        ("binary", "10 - 4"),
        ("binary", "5 + 3"),
        ("binary", "6 * 7"),
        ("binary", "10 / 4"),
        ("binary", "7 mod 3"),
        ("binary", "7 div 3"),
        ("binary", "1 + 2 * 3"),
        ("binary", "(1 + 2) * 3"),
        ("binary", "1 - 2 - 3"),
        ("binary", "8 / 4 / 2"),
        ("binary", "2 * 3 / 4 mod 5"),
        ("binary", "200 + (stateIdx * 100)"),
        ("binary", "baseLocationId + sm.states->indexOf(tr.targetState) - 1 + 2"),
        ("binary", "'Hello' + ' ' + 'World'"),
        ("binary", "firstName + ' ' + lastName"),
        ("binary", "a = b"),
        ("binary", "a <> b"),
        ("binary", "a < b"),
        ("binary", "a > b"),
        ("binary", "a <= b"),
        ("binary", "a >= b"),
        ("binary", "a = b = c"),
        ("binary", "1 + 2 = 3"),
        ("binary", "a < b + 1"),
        ("binary", "a and b"),
        ("binary", "a or b"),
        ("binary", "a xor b"),
        ("binary", "a implies b"),
        ("binary", "a and b or c"),
        ("binary", "a or b and c"),
        ("binary", "a or b xor c"),
        ("binary", "a and b and c"),
        ("binary", "a implies b implies c"),
        ("binary", "a or b implies c and d"),
        ("binary", "a = 1 and b = 2 or c = 3"),
        ("binary", "(a or b) and c"),
        ("binary", "a - -1"),
        ("binary", "a-1"),
        ("binary", "a -1"),
        ("binary", "x.y-1"),
        ("binary", "f()-1"),
        ("binary", "1-1"),
        ("binary", "a*-1"),
        ("binary", "a.size() / 2"),
        ("unary", "not a"),
        ("unary", "not not a"),
        ("unary", "-a"),
        ("unary", "- -a"),
        ("unary", "-(1 + 2)"),
        ("unary", "not a and b"),
        ("unary", "-a * b"),
        ("unary", "not x.isEmpty()"),
        ("unary", "-x.size"),
        ("unary", "- 1"),
        ("unary", "not (a or b)"),

        // Collection literals
        ("collection", "Sequence{}"),
        ("collection", "Sequence{1, 2, 3}"),
        ("collection", "OrderedSet{1, 2}"),
        ("collection", "Set{'a'}"),
        ("collection", "Bag{'a', 'a'}"),
        ("collection", "Collection{1}"),
        ("collection", "Sequence{1 + 1, f(x), Sequence{2}}"),
        ("collection", "Sequence{'a', 'b', 'c'}->size()"),
        ("collection", "Sequence{1, 2}.item()"),

        // Type and enumeration literals, qualified names
        ("qualified", "ecore::EClass"),
        ("qualified", "pkg::Enum::literal"),
        ("qualified", "a::b::Enum::literal"),
        ("qualified", "x.oclIsKindOf(ecore::EClass)"),
        ("qualified", "e.oclIsKindOf(AndExpression)"),
        ("qualified", "e.oclIsTypeOf(a::b::C)"),
        ("qualified", "e.oclAsType(p::q::r::T).name"),
        ("qualified", "oclIsKindOf(ecore::EClass)"),
        ("qualified", "xs->select(oclIsKindOf(a::B::C))"),
        ("qualified", "xs->filter(pkg::Type)"),
        ("qualified", "x = pkg::Enum::literal"),
        ("qualified", "x = ecore::EClass"),

        // Type operations
        ("type", "e.oclIsKindOf(T)"),
        ("type", "e.oclIsTypeOf(T)"),
        ("type", "e.oclAsType(T)"),
        ("type", "oclAsType(T)"),
        ("type", "e.oclAsType(IntegerConstant).anIntegerValue"),
        ("type", "tr.booleanExpression.oclAsType(NotExpression).theExpression.oclAsType(EqualExpression).leftExpression.oclAsType(IntegerConstant).anIntegerValue"),

        // Parentheses and mixtures
        ("mixed", "(x)"),
        ("mixed", "((x))"),
        ("mixed", "(a + b).size"),
        ("mixed", "(xs->select(x | x > 1))->size()"),
        ("mixed", "xs->select(x | x > 1 and x < 5)->collect(x | x * 2)->first()"),
        ("mixed", "if xs->isEmpty() then 'none' else xs->first().name endif"),
        ("mixed", "let n = xs->size() in if n > 1 then n - 1 else 0 endif"),
        ("mixed", "not xs->exists(x | x.oclIsKindOf(Foo) and x.name = 'a')"),
        ("mixed", "a.b(c)->select(d | d.e(f))->size() + g(h)"),
        ("mixed", "Sequence{a, b}->collect(x | x.name + '!')"),
        ("mixed", "self.name + '.' + self.kind.toString()"),
        ("mixed", "xs->collect(x | x->select(y | y > x))"),
        ("mixed", "xs->select(x | ys->exists(y | y = x))->size() > 0"),
    ]

    /// Expressions that must be rejected.
    static let invalid: [String] = [
        "",
        "+",
        "1 +",
        "(1",
        "1)",
        "x.",
        "x->",
        "xs->select(x | )",
        "if a then b endif",
        "if a then b else c",
        "let x = 1",
        "let x in 1",
        "Sequence{1, 2",
        "f(1, ",
        "a and",
        "not",
        "1 2",
        "xs->indexOf",
        "x.1",
        "'unterminated",
    ]
}
